SIM_VER=simmetrix-simmodsuite-2025.0-250108dev-llxq6skz2cuht5glyftojzw5tkgodnub
SIM_ARCHOS=x64_rhel8_gcc83
PSPLINE_DIR=/users/riazu2/lore.scorec.rpi.edu/Tools/install/PSPLINE/gcc12.3.0
OMEGAH_DIR=/users/riazu2/lore.scorec.rpi.edu/Tools/install/OmegaH/gcc12.3.0
ADIOS2_DIR=/opt/scorec/spack/rhel9/v0201_4/install/linux-rhel9-x86_64/gcc-12.3.0/adios2-2.9.0-nztsv7oahftcta2dntesql2wkep6kdfp
PREFIX=/users/riazu2/lore.scorec.rpi.edu/STOMMS_dev/STOMMS/install
CMAKETYPE=Debug
cmake .. \
  -DCMAKE_C_COMPILER=mpicc \
  -DCMAKE_CXX_COMPILER=mpicxx \
  -DCMAKE_Fortran_COMPILER=mpif90 \
  -DCMAKE_C_FLAGS="-g -O0" \
  -DCMAKE_CXX_FLAGS="-g -O0" \
  -DCMAKE_Fortran_FLAGS="-fpic -ffree-line-length-0"\
  -DSIM_MPI=mpich4.1.1 \
  -DSIMMETRIX_INCLUDE_DIR=/opt/scorec/spack/rhel9/v0201_4/install/linux-rhel9-x86_64/gcc-12.3.0/$SIM_VER/include \
  -DSIMMETRIX_LIB_DIR=/opt/scorec/spack/rhel9/v0201_4/install/linux-rhel9-x86_64/gcc-12.3.0/$SIM_VER/lib/$SIM_ARCHOS \
  -DPSPLINE_INCLUDE_DIR=$PSPLINE_DIR/mod \
  -DPSPLINE_LIB_DIR=$PSPLINE_DIR/lib \
  -DOmega_h_DIR=$OMEGAH_DIR/lib64/cmake/Omega_h \
  -DADIOS2_INCLUDE_DIR=$ADIOS2_DIR/include \
  -DADIOS2_LIB_DIR=$ADIOS2_DIR/lib64 \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_BUILD_TYPE=$CMAKETYPE
